[package]
name = "gregcsokas-backend-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = []

[dependencies]

[dependencies.axum]
version = "0.8.1"
features = [
    "default",
    "http2",
]